---
title: "Comparison of CPDs"
author: "Hsuan Lee"
output: pdf_document
---
```{r}
# install.packages('caret')
library(caret) # for confusion matrix
```

# Confusion Matrix

```{r}
# rep = number of datasets we have
rep <- 15
```

**For the datasets with no changepoints**

Reference:
```{r}
ref_ncp <- 0
```

Prediction:

1. BOCPD

- Sender Effect
```{r}
pred_send_BOCD_ncp <- 0

for (i in 1:15) {
  # remove the first value of the vector, as BOCPD function indicates the first window as CP all the time
  locat_cp <- locat_BOCD_ncp_send[[i]][-1]
  pred_send_BOCD_ncp[i] <- length(locat_cp)
  print(pred_send_BOCD_ncp)
}
```







```{r}
conf_matrix <- function(pred_CPs, # e.g. locat_BOCD_1cp_out_same.all
                        true_CPs, # a vector
                        threshold = 5, # range that still can be recognized as correct CP identification
                        window_parameters # the window given parameters, e.g. fixmw_send_1cp_param
                        ){
  
  true_CPs_locate <- list()
  for (i in 1:length(pred_CPs)) {
    # assign 0 to the no CP windows, 1 to CP windows
    true_CPs_locate[[i]] <- rep(0, length(window_parameters[[i]]))
    true_CPs_locate[[i]][true_CPs] <- 1
  }

  pred_CPs_locate <- list()
  for (i in 1::length(pred_CPs)) {
    # assign 0 to the no CP windows, 1 to CP windows
    pred_CPs_locate[[i]] <- rep(0, length(window_parameters[[i]]))
    # assign the predicted changepoint as 1
    pred_CPs_locate[[i]][pred_CPs[[i]]] <- 1
  }
}












pred_CPs_locate <- list()
  for (i in 1:15) {
    # assign 0 to the no CP windows, 1 to CP windows
    pred_CPs_locate[[i]] <- rep(0, length(fixmw_send_1cp_param[[i]]))
    # assign the predicted changepoint as 1
    pred_CPs_locate[[i]][locat_BOCD_1cp_out[[i]]] <- 1
  }


```











```{r}
# number of windows of each dataset
length_ncp <- list()
for (i in 1:rep) {
  length_ncp[[i]] <- length(fixmw_send_ncp_param[[i]])
}

# create the true changepoints locations
ref_ncp <- list()
for (i in 1:rep) {
  ref_ncp[[i]] <- rep(0, length_ncp[[i]])
}
```

Prediction:

1. BOCPD

- Sender Effect
```{r}
pred_send_BOCD_ncp <- list()
for (i in 1:rep) {
  # remove the first value of the vector, as BOCPD function indicates the first window as CP all the time
  locat_cp <- locat_BOCD_ncp_send[[i]][-1]
  pred_send_BOCD_ncp[[i]] <- rep(0, length_ncp[[i]])
  
  # assign the predicted changepoint as 1
  pred_send_BOCD_ncp[[i]][locat_cp] <- 1
}
```






```{r}
locat_BOCD_ncp_send[[5]][-1][1]
```




```{r}
# true_CPs has to be a matrix
conf_matrix <- function(pred_CPs, # e.g. locat_BOCD_1cp_out_same.all
                        true_CPs, # a matrix / vector
                        window_parameters # the window given parameters, e.g. fixmw_send_1cp_param
                        ){
  confusionmatrix <- vector(mode='list', length = length(window_parameters))
  
  for (i in 1:length(pred_CPs)) {
    
    confusionmatrix[[i]] <- 
      for (detet_cp in 0:length(pred_CPs[[i]])) {
        if(pred_CPs[[i]][detet_cp] == true_CPs[1] | true_CPs[2] | true_CPs[3]
           | true_CPs[4] | true_CPs[5] | true_CPs[6] | true_CPs[7] 
           | true_CPs[8] | true_CPs[9] | true_CPs[10] | true_CPs[11]
           | true_CPs[12] | true_CPs[13] | true_CPs[14] | true_CPs[15]
           | true_CPs[16] | true_CPs[17] | true_CPs[18] | true_CPs[19]
           | true_CPs[20] | true_CPs[21] | true_CPs[22]){
        "TP"
      } else("FP")
      }
      
      
      

    #confusionmatrix[[i]] <- true_CPs[,i]
    
  }
  return(confusionmatrix)
}

















conf_matrix <- function(pred_CPs, # e.g. locat_BOCD_1cp_out_same.all
                        true_CPs, # a matrix / vector
                        window_parameters # the window given parameters, e.g. fixmw_send_1cp_param
){
  
  positive <- vector(mode='list', length = length(window_parameters))
  negative <- vector(mode='list', length = length(window_parameters))
  
  for (i in 1:length(pred_CPs)) {
    
    for (detet_cp in 0:length(pred_CPs[[i]])) {
      
      positive[[i]][detect_cp] <- 
        if (length(pred_CPs[[i]][detect_cp]) > 0 && pred_CPs[[i]][detect_cp] %in% true_CPs) {
          "TP"
        } else {
          "FP"
        }
      
      negative[[i]][detect_cp] <- 
        if (!(pred_CPs[[i]][detet_cp] %in% true_CPs)) {
          "FN"
        }
      
      }
      
    #confusionmatrix[[i]] <- true_CPs[,i]
    
  }
  return(positive, negative)
}







conf_matrix <- function(pred_CPs, # e.g. locat_BOCD_1cp_out_same.all
                        true_CPs, # a matrix, no. of col = no. of cp; row = acceptable detected cp
                        window_parameters # the window given parameters, e.g. fixmw_send_1cp_param
){
  
  positive <- vector(mode='list', length = length(window_parameters))
  negative <- vector(mode='list', length = length(window_parameters))
  
  for (i in 1:length(pred_CPs)) {
    
    for (detect_cp in 0:length(pred_CPs[[i]])) {
      
      positive[[i]][detect_cp] <- 
        if (length(pred_CPs[[i]][detect_cp]) > 0 && pred_CPs[[i]][detect_cp] %in% true_CPs) {
          "TP"
        } else {
          "FP"
        }
    }
    
    FN <- list()
    FN[[i]] <- ncol(true_CPs) - sum(positive[[i]] == "TP")
    
    negative[[]]
    
    
    
    
    
    
    
  }
  return(positive)
}
















conf_matrix <- function(pred_CPs, # e.g. locat_BOCD_1cp_out_same.all
                        true_CPs, # a matrix, no. of col = no. of cp; row = acceptable detected cp
                        window_parameters # the window given parameters, e.g. fixmw_send_1cp_param
){
  
  confusionmatrix <- vector(mode='list', length = length(window_parameters))
  leveling <- list()
  table <- list()
  
  for (i in 1:length(pred_CPs)) {
    
    for (detect_cp in 0:length(pred_CPs[[i]])) {
      
      confusionmatrix[[i]][detect_cp] <- 
        if (length(pred_CPs[[i]][detect_cp]) > 0 && pred_CPs[[i]][detect_cp] %in% true_CPs) {
          "TP"
        } else {
          "FP"
        }
    }
    
    FN <- list()
    FN[[i]] <- ncol(true_CPs) - sum(confusionmatrix[[i]] == "TP")
    
    confusionmatrix[[i]] <- c(confusionmatrix[[i]], rep("FN", FN[[i]]))
    
    level <- c("TP", "FP", "FN", "TN")
    leveling[[i]] <- factor(confusionmatrix[[i]], level)
    table[[i]] <- table(leveling[[i]])
    
  }
  return(list(confusionmatrix = confusionmatrix, 
              table = table))
}





level <- c("TP", "FP", "FN", "TN")
b <- c("TP", "FN")
table <- factor(b, level)
table(table)





if(pred_CPs[[i]][i] == true_CPs[1,i] | true_CPs[2,i] | true_CPs[3,i]
           | true_CPs[4,i] | true_CPs[5,i] | true_CPs[6,i] | true_CPs[7,i] 
           | true_CPs[8,i] | true_CPs[9,i] | true_CPs[10,i]){
        "TP"
      } else("FP")

locat_BOCD_1cp_ine[[1]][1]

true_cp <- matrix(data = c(58, 59, 60, 61, 62, 63, 57, 56, 55, 54, 53), ncol = 1)
  
  
  

a <- conf_matrix(pred_CPs = locat_BOCD_1cp_ine, true_CPs = true_cp, window_parameters = fixmw_ine_1cp_param)

length(locat_BOCD_1cp_ine)
```













# Create the function for MSE
```{r}
MSE_CPD <- function(pred_CPs, actu_CPs){
  
  single_MSE <- 0 # create an blank vector for storing
  
  for (CP in 1:length(pred_CPs)) {
    # MSE of each CP
    single_MSE[CP] <- (pred_CPs[CP] - actu_CPs[CP])^2
    }
  
  # sum the MSE from each CP
  sum_MSE <- sum(single_MSE)
  
  # MSE
  MSE <- sum_MSE / length(pred_CPs)
  
  return(MSE)
}
```

# Create the function for MSD
```{r}
MSD_CPD <- function(pred_CPs, actu_CPs){
  
  single_MSD <- 0 # create an blank vector for storing
  
  for (CP in 1:length(pred_CPs)) {
    # MSD of each CP
    single_MSD[CP] <- pred_CPs[CP] - actu_CPs[CP]
    }
  
  # sum the MSD from each CP
  sum_MSD <- sum(single_MSD)
  
  # MSD
  MSD <- sum_MSD / length(pred_CPs)
  
  return(MSD)
}
```
































